twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
        # form_themes: ['bootstrap_5_layout.html.twig', 'form/my_theme.html.twig']


